-- Lodestone database schema (reference DDL).
-- Authoritative schema is generated by EF Core migrations in Lodestone.Infrastructure/Data/Migrations.
-- This file documents the intended tables for reviewers and DBAs.

-- Example (illustrative only):
-- CREATE TABLE StudentProfiles ( Id INT IDENTITY PRIMARY KEY, UserId NVARCHAR(450) NOT NULL, ... );
